apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-17T19:29:05Z"
  labels:
    app: epimetheus
  name: epimetheus
spec:
  containers:
    - args:
        - /opt/bitnami/scripts/redis/run.sh
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      image: docker.io/bitnami/redis:7.2
      name: redis
      ports:
        - containerPort: 5000
          hostPort: 5000
        - containerPort: 6379
          hostPort: 6379
      securityContext:
        runAsNonRoot: true
      volumeMounts:
        - mountPath: /bitnami/redis/data
          name: epimetheus_redis-pvc
    - env:
        - name: OLLAMA_BASE_URL
          value: http://ollama.ai.local
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: slack-bot-token
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: slack-app-token
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: slack-signing-secret
      image: localhost/epimetheus-test
      name: epimetheus-app
      securityContext:
        runAsNonRoot: true
  volumes:
    - name: epimetheus_redis-pvc
      persistentVolumeClaim:
        claimName: epimetheus_redis
